using System;
using System.Collections.Generic;

namespace BlogML2Hugo
{
    public class TechnologyToolboxImageUrlMapper : IUrlMapper
    {
        private const string _newImageHost = "assets.technologytoolbox.com";
        private const string _oldImageHost = "www.technologytoolbox.com";

        private const string _newImageBasePath = "/blog/jjameson/Images";
        private const string _oldImageBasePath =
            "/blog/images/www_technologytoolbox_com/blog/jjameson";

        private Dictionary<string, Uri> _imageUrlMap = new Dictionary<string, Uri>();

        public TechnologyToolboxImageUrlMapper()
        {
            _imageUrlMap = new Dictionary<string, Uri>();

            // This is considered "throwaway" code, so don't bother with making
            // the list of mapped image URLs configurable

            AddMappedImageUrl("7/o_1%20-%20Initial%20build%20and%20deployment.png",
                "Development/1-Initial-build-and-deployment-1210x523.png");
            AddMappedImageUrl("7/r_1%20-%20Initial%20build%20and%20deployment.png",
                "Development/1-Initial-build-and-deployment-600x259.png");
            AddMappedImageUrl("7/o_2%20-%20Subsequent%20build%20and%20deployment.png",
                "Development/2-Subsequent-build-and-deployment-829x375.png");
            AddMappedImageUrl("7/r_2%20-%20Subsequent%20build%20and%20deployment.png",
                "Development/2-Subsequent-build-and-deployment-600x271.png");
            AddMappedImageUrl("7/o_3%20-%20Automated%20build%20and%20deployment.png",
                "Development/3-Automated-build-and-deployment-926x530.png");
            AddMappedImageUrl("7/r_3%20-%20Automated%20build%20and%20deployment.png",
                "Development/3-Automated-build-and-deployment-600x343.png");
            AddMappedImageUrl("7/o_4%20-%20Installing%20the%20Beta%201%20version%20to%20TEST.png",
                "Development/4-Installing-the-Beta-1-version-to-TEST-940x538.png");
            AddMappedImageUrl("7/r_4%20-%20Installing%20the%20Beta%201%20version%20to%20TEST.png",
                "Development/4-Installing-the-Beta-1-version-to-TEST-600x343.png");
            AddMappedImageUrl("7/o_5%20-%20Installing%20the%20RC1%20version%20to%20TEST.png",
                "Development/5-Installing-the-RC1-version-to-TEST-1382x809.png");
            AddMappedImageUrl("7/r_5%20-%20Installing%20the%20RC1%20version%20to%20TEST.png",
                "Development/5-Installing-the-RC1-version-to-TEST-600x351.png");
            AddMappedImageUrl("7/o_6%20-%20Installing%20the%20RC2%20version%20to%20TEST.png",
                "Development/6-Installing-the-RC2-version-to-TEST-1381x808.png");
            AddMappedImageUrl("7/r_6%20-%20Installing%20the%20RC2%20version%20to%20TEST.png",
                "Development/6-Installing-the-RC2-version-to-TEST-600x351.png");
            AddMappedImageUrl("7/o_7%20-%20Installing%20the%20V1.0%20release%20to%20PROD.png",
                "Development/7-Installing-the-V1.0-release-to-PROD-1382x807.png");
            AddMappedImageUrl("7/r_7%20-%20Installing%20the%20V1.0%20release%20to%20PROD.png",
                "Development/7-Installing-the-V1.0-release-to-PROD-600x350.png");
            AddMappedImageUrl("8/o_After%20restricting%20MaxPatchCacheSize.png",
                "Infrastructure/After-restricting-MaxPatchCacheSize-857x704.png");
            AddMappedImageUrl("8/r_After%20restricting%20MaxPatchCacheSize.png",
                "Infrastructure/After-restricting-MaxPatchCacheSize-600x493.png");
            AddMappedImageUrl("9/o_AJAX%20in%20SharePoint.png",
                "SharePoint/AJAX-in-SharePoint-989x688.png");
            AddMappedImageUrl("9/r_AJAX%20in%20SharePoint.png",
                "SharePoint/AJAX-in-SharePoint-600x417.png");
            AddMappedImageUrl("7/o_ASP.NET%20Trace%20Sample.png",
                "Development/ASP.NET-Trace-Sample-736x931.png");
            AddMappedImageUrl("7/r_ASP.NET%20Trace%20Sample.png",
                "Development/ASP.NET-Trace-Sample-474x600.png");
            AddMappedImageUrl("7/o_ASP.NET%20Trace%20Viewer.png",
                "Development/ASP.NET-Trace-Viewer-705x314.png");
            AddMappedImageUrl("7/r_ASP.NET%20Trace%20Viewer.png",
                "Development/ASP.NET-Trace-Viewer-600x267.png");
            AddMappedImageUrl("7/o_ASP.NET%20Yellow%20Page%20of%20Death.png",
                "Development/ASP.NET-Yellow-Page-of-Death-1301x639.png");
            AddMappedImageUrl("7/r_ASP.NET%20Yellow%20Page%20of%20Death.png",
                "Development/ASP.NET-Yellow-Page-of-Death-600x295.png");
            AddMappedImageUrl("7/o_Branch-Plan-Basic.png",
                "Development/Branch-Plan-Basic-820x356.png");
            AddMappedImageUrl("7/r_Branch-Plan-Basic.png",
                "Development/Branch-Plan-Basic-600x260.png");
            AddMappedImageUrl("7/o_Branch-Plan-Problematic.png",
                "Development/Branch-Plan-Problematic-820x356.png");
            AddMappedImageUrl("7/r_Branch-Plan-Problematic.png",
                "Development/Branch-Plan-Problematic-600x260.png");
            AddMappedImageUrl("15/o_Broken%20Tibia%20-%20External%20Fixators.jpg",
                "Personal/Broken-Tibia-External-Fixators-1024x768.jpg");
            AddMappedImageUrl("15/r_Broken%20Tibia%20-%20External%20Fixators.jpg",
                "Personal/Broken-Tibia-External-Fixators-600x450.jpg");
            AddMappedImageUrl("7/o_Caelum%20-%20Default.master.png",
                "Development/Caelum-Default.master-1021x241.png");
            AddMappedImageUrl("7/r_Caelum%20-%20Default.master.png",
                "Development/Caelum-Default.master-600x142.png");
            AddMappedImageUrl("7/o_Caelum%20-%20Initial%20source%20tree.png",
                "Development/Caelum-Initial-source-tree-789x552.png");
            AddMappedImageUrl("7/r_Caelum%20-%20Initial%20source%20tree.png",
                "Development/Caelum-Initial-source-tree-600x420.png");
            AddMappedImageUrl("7/o_Constrained%20Table.png",
                "Development/Constrained-Table-559x166.png");
            AddMappedImageUrl("9/o_Custom%20Error%20Page.png",
                "SharePoint/Custom-Error-Page-1024x276.png");
            AddMappedImageUrl("9/r_Custom%20Error%20Page.png",
                "SharePoint/Custom-Error-Page-600x162.png");
            AddMappedImageUrl("7/o_DebugView.png",
                "Development/DebugView-946x300.png");
            AddMappedImageUrl("7/r_DebugView.png",
                "Development/DebugView-600x190.png");
            AddMappedImageUrl("9/o_DefaultMaster_DefaultPageLayout.png",
                "SharePoint/DefaultMaster_DefaultPageLayout-1064x504.png");
            AddMappedImageUrl("9/r_DefaultMaster_DefaultPageLayout.png",
                "SharePoint/DefaultMaster_DefaultPageLayout-600x284.png");
            AddMappedImageUrl("10/o_Development-cheat-sheet-Dow-ELN-Main-branch.png",
                "My-System/Development-cheat-sheet-Dow-ELN-Main-branch-1328x1021.png");
            AddMappedImageUrl("10/r_Development-cheat-sheet-Dow-ELN-Main-branch.png",
                "My-System/Development-cheat-sheet-Dow-ELN-Main-branch-600x461.png");
            AddMappedImageUrl("10/o_Development-cheat-sheet-Fabrikam-Demo-Main-branch.png",
                "My-System/Development-cheat-sheet-Fabrikam-Demo-Main-branch-1098x719.png");
            AddMappedImageUrl("10/r_Development-cheat-sheet-Fabrikam-Demo-Main-branch.png",
                "My-System/Development-cheat-sheet-Fabrikam-Demo-Main-branch-600x393.png");
            AddMappedImageUrl("10/o_Development-cheat-sheet-Fabrikam-Demo-SharePointExtranet-branch.png",
                "My-System/Development-cheat-sheet-Fabrikam-Demo-SharePointExtranet-branch-1190x1040.png");
            AddMappedImageUrl("10/r_Development-cheat-sheet-Fabrikam-Demo-SharePointExtranet-branch.png",
                "My-System/Development-cheat-sheet-Fabrikam-Demo-SharePointExtranet-branch-600x524.png");
            AddMappedImageUrl("8/o_Disk%20Benchmarks%20-%20Baseline.png",
                "Infrastructure/Disk-Benchmarks-Baseline-823x954.png");
            AddMappedImageUrl("8/r_Disk%20Benchmarks%20-%20Baseline.png",
                "Infrastructure/Disk-Benchmarks-Baseline-518x600.png");
            AddMappedImageUrl("8/o_Disk%20Benchmarks%20-%20WOLVERINE.png",
                "Infrastructure/Disk-Benchmarks-WOLVERINE-823x554.png");
            AddMappedImageUrl("8/r_Disk%20Benchmarks%20-%20WOLVERINE.png",
                "Infrastructure/Disk-Benchmarks-WOLVERINE-600x404.png");
            AddMappedImageUrl("8/o_Disk%20Usage-COLOSSUS%20(after%20WS2008%20SP2%20install).png",
                "Infrastructure/Disk-Usage-COLOSSUS-(after-WS2008-SP2-install)-758x574.png");
            AddMappedImageUrl("8/r_Disk%20Usage-COLOSSUS%20(after%20WS2008%20SP2%20install).png",
                "Infrastructure/Disk-Usage-COLOSSUS-(after-WS2008-SP2-install)-600x454.png");
            AddMappedImageUrl("8/r_Disk%20Usage-foobar.jpg",
                "Infrastructure/Disk-Usage-foobar-600x492.jpg");
            AddMappedImageUrl("8/o_Disk%20Usage-foobar.jpg",
                "Infrastructure/Disk-Usage-foobar-775x635.jpg");
            AddMappedImageUrl("8/o_Disk%20Usage%20-%20FOOBAR7%20-%20Baseline.png",
                "Infrastructure/Disk-Usage-FOOBAR7-Baseline-991x760.png");
            AddMappedImageUrl("8/r_Disk%20Usage%20-%20FOOBAR7%20-%20Baseline.png",
                "Infrastructure/Disk-Usage-FOOBAR7-Baseline-600x460.png");
            AddMappedImageUrl("8/r_Disk%20usage%20-%20Vista%20Ultimate%20x64%20(baseline).jpg",
                "Infrastructure/Disk-usage-Vista-Ultimate-x64-(baseline)-537x600.jpg");
            AddMappedImageUrl("8/o_Disk%20usage%20-%20Vista%20Ultimate%20x64%20(baseline).jpg",
                "Infrastructure/Disk-usage-Vista-Ultimate-x64-(baseline)-840x939.jpg");
            AddMappedImageUrl("8/r_Disk%20usage%20-%20Vista%20with%20SP1%20and%20products.jpg",
                "Infrastructure/Disk-usage-Vista-with-SP1-and-products-532x600.jpg");
            AddMappedImageUrl("8/o_Disk%20usage%20-%20Vista%20with%20SP1%20and%20products.jpg",
                "Infrastructure/Disk-usage-Vista-with-SP1-and-products-784x885.jpg");
            AddMappedImageUrl("8/r_Disk%20Usage-win2k3ee-base%20(after%20SP2%20install).jpg",
                "Infrastructure/Disk-Usage-win2k3ee-base-(after-SP2-install)-600x418.jpg");
            AddMappedImageUrl("8/o_Disk%20Usage-win2k3ee-base%20(after%20SP2%20install).jpg",
                "Infrastructure/Disk-Usage-win2k3ee-base-(after-SP2-install)-768x535.jpg");
            AddMappedImageUrl("8/r_Disk%20Usage-win2k3ee-base%20(SP1%20slipstream).jpg",
                "Infrastructure/Disk-Usage-win2k3ee-base-(SP1-slipstream)-600x419.jpg");
            AddMappedImageUrl("8/o_Disk%20Usage-win2k3ee-base%20(SP1%20slipstream).jpg",
                "Infrastructure/Disk-Usage-win2k3ee-base-(SP1-slipstream)-768x536.jpg");
            AddMappedImageUrl("8/r_Disk%20Usage-win2k3ee-base%20(SP2%20slipstreamed).jpg",
                "Infrastructure/Disk-Usage-win2k3ee-base-(SP2-slipstreamed)-600x419.jpg");
            AddMappedImageUrl("8/o_Disk%20Usage-win2k3ee-base%20(SP2%20slipstreamed).jpg",
                "Infrastructure/Disk-Usage-win2k3ee-base-(SP2-slipstreamed)-767x536.jpg");
            AddMappedImageUrl("8/o_Disk%20usage%20-%20Windows%20Server%202008%20(baseline).jpg",
                "Infrastructure/Disk-usage-Windows-Server-2008-(baseline)-800x600.jpg");
            AddMappedImageUrl("8/r_Disk%20usage%20-%20Windows%20Server%202008%20(baseline).jpg",
                "Infrastructure/Disk-usage-Windows-Server-2008-(baseline)-600x450.jpg");
            AddMappedImageUrl("8/o_Disk%20Usage%20-%20WOLVERINE%20-%20Baseline.png",
                "Infrastructure/Disk-Usage-WOLVERINE-Baseline-927x784.png");
            AddMappedImageUrl("8/r_Disk%20Usage%20-%20WOLVERINE%20-%20Baseline.png",
                "Infrastructure/Disk-Usage-WOLVERINE-Baseline-600x507.png");
            AddMappedImageUrl("8/o_Disk%20Usage-WS2008-R2%20(with%20SQL%202008%20SP1).png",
                "Infrastructure/Disk-Usage-WS2008-R2-(with-SQL-2008-SP1)-1024x727.png");
            AddMappedImageUrl("8/r_Disk%20Usage-WS2008-R2%20(with%20SQL%202008%20SP1).png",
                "Infrastructure/Disk-Usage-WS2008-R2-(with-SQL-2008-SP1)-600x426.png");
            AddMappedImageUrl("8/o_Disk%20Usage%20-%20ws2008std-x64-SP2.png",
                "Infrastructure/Disk-Usage-ws2008std-x64-SP2-801x576.png");
            AddMappedImageUrl("8/r_Disk%20Usage%20-%20ws2008std-x64-SP2.png",
                "Infrastructure/Disk-Usage-ws2008std-x64-SP2-600x431.png");
            AddMappedImageUrl("8/o_Disk%20Usage-WS2008-x64%20(WS2008%20SP2%20-%20compcln).png",
                "Infrastructure/Disk-Usage-WS2008-x64-(WS2008-SP2-compcln)-801x573.png");
            AddMappedImageUrl("8/r_Disk%20Usage-WS2008-x64%20(WS2008%20SP2%20-%20compcln).png",
                "Infrastructure/Disk-Usage-WS2008-x64-(WS2008-SP2-compcln)-600x429.png");
            AddMappedImageUrl("9/o_DR.DADA%20-%201.png",
                "SharePoint/DR.DADA-1-355x178.png");
            AddMappedImageUrl("9/o_DR.DADA%20-%202.png",
                "SharePoint/DR.DADA-2-325x1066.png");
            AddMappedImageUrl("9/r_DR.DADA%20-%202.png",
                "SharePoint/DR.DADA-2-183x600.png");
            AddMappedImageUrl("9/o_DR.DADA%20-%203.png",
                "SharePoint/DR.DADA-3-996x341.png");
            AddMappedImageUrl("9/r_DR.DADA%20-%203.png",
                "SharePoint/DR.DADA-3-600x205.png");
            AddMappedImageUrl("7/r_Entity-Model-Caelum-Step-2.png",
                "Development/Entity-Model-Caelum-Step-2-431x400.png");
            AddMappedImageUrl("9/o_Environment%20Variables.png",
                "SharePoint/Environment-Variables-394x436.png");
            AddMappedImageUrl("7/o_Environment-Variables-Fabrikam-Extranet.png",
                "Development/Environment-Variables-Fabrikam-Extranet-394x436.png");
            AddMappedImageUrl("7/o_Expression%20Web%20-%20My%20MSDN%20Blog.png",
                "Development/Expression-Web-My-MSDN-Blog-1251x1040.png");
            AddMappedImageUrl("7/r_Expression%20Web%20-%20My%20MSDN%20Blog.png",
                "Development/Expression-Web-My-MSDN-Blog-600x499.png");
            AddMappedImageUrl("7/o_Expression%20Web%20-%20My%20Technology%20Toolbox%20Blog.png",
                "Development/Expression-Web-My-Technology-Toolbox-Blog-1920x1040.png");
            AddMappedImageUrl("7/r_Expression%20Web%20-%20My%20Technology%20Toolbox%20Blog.png",
                "Development/Expression-Web-My-Technology-Toolbox-Blog-600x325.png");
            AddMappedImageUrl("9/o_FabrikamDefaultMaster-CustomLayout.png",
                "SharePoint/FabrikamDefaultMaster-CustomLayout-1045x628.png");
            AddMappedImageUrl("9/r_FabrikamDefaultMaster-CustomLayout.png",
                "SharePoint/FabrikamDefaultMaster-CustomLayout-600x361.png");
            AddMappedImageUrl("9/o_FabrikamDefaultMaster-DefaultLayout.png",
                "SharePoint/FabrikamDefaultMaster-DefaultLayout-1062x530.png");
            AddMappedImageUrl("9/r_FabrikamDefaultMaster-DefaultLayout.png",
                "SharePoint/FabrikamDefaultMaster-DefaultLayout-600x299.png");
            AddMappedImageUrl("9/o_FabrikamDefaultMaster-DefaultLayout2.png",
                "SharePoint/FabrikamDefaultMaster-DefaultLayout2-1045x756.png");
            AddMappedImageUrl("9/r_FabrikamDefaultMaster-DefaultLayout2.png",
                "SharePoint/FabrikamDefaultMaster-DefaultLayout2-600x434.png");
            AddMappedImageUrl("9/o_Fabrikam%20Extranet%20-%20home%20page.png",
                "SharePoint/Fabrikam-Extranet-home-page-1010x467.png");
            AddMappedImageUrl("9/r_Fabrikam%20Extranet%20-%20home%20page.png",
                "SharePoint/Fabrikam-Extranet-home-page-600x277.png");
            AddMappedImageUrl("7/o_Firefox%20-%20Firebug.png",
                "Development/Firefox-Firebug-801x738.png");
            AddMappedImageUrl("7/r_Firefox%20-%20Firebug.png",
                "Development/Firefox-Firebug-380x350.png");
            AddMappedImageUrl("7/o_Firefox%20-%20Screengrab.png",
                "Development/Firefox-Screengrab-801x738.png");
            AddMappedImageUrl("7/r_Firefox%20-%20Screengrab.png",
                "Development/Firefox-Screengrab-380x350.png");
            AddMappedImageUrl("7/o_Firefox%20-%20Web%20Developer.png",
                "Development/Firefox-Web-Developer-801x738.png");
            AddMappedImageUrl("7/r_Firefox%20-%20Web%20Developer.png",
                "Development/Firefox-Web-Developer-380x350.png");
            AddMappedImageUrl("7/o_Firefox%20-%20YSlow.png",
                "Development/Firefox-YSlow-843x1119.png");
            AddMappedImageUrl("7/r_Firefox%20-%20YSlow.png",
                "Development/Firefox-YSlow-286x380.png");
            AddMappedImageUrl("9/o_FOOBAR2%20Snapshots.png",
                "SharePoint/FOOBAR2-Snapshots-1051x652.png");
            AddMappedImageUrl("9/r_FOOBAR2%20Snapshots.png",
                "SharePoint/FOOBAR2-Snapshots-600x372.png");
            AddMappedImageUrl("9/o_FOOBAR5%20Snapshots.png",
                "SharePoint/FOOBAR5-Snapshots-1056x674.png");
            AddMappedImageUrl("9/r_FOOBAR5%20Snapshots.png",
                "SharePoint/FOOBAR5-Snapshots-600x383.png");
            AddMappedImageUrl("7/o_General%20Site%20-%20Generic%20(Glycomics%20Solution).jpg",
                "Development/General-Site-Generic-(Glycomics-Solution)-939x747.jpg");
            AddMappedImageUrl("7/r_General%20Site%20-%20Generic%20(Glycomics%20Solution).jpg",
                "Development/General-Site-Generic-(Glycomics-Solution)-600x477.jpg");
            AddMappedImageUrl("7/o_General%20Site%20-%20Generic%20(Page%20Layout).jpg",
                "Development/General-Site-Generic-(Page-Layout)-770x627.jpg");
            AddMappedImageUrl("7/r_General%20Site%20-%20Generic%20(Page%20Layout).jpg",
                "Development/General-Site-Generic-(Page-Layout)-600x489.jpg");
            AddMappedImageUrl("7/o_General%20Site%20-%20Press%20Release%20(857).jpg",
                "Development/General-Site-Press-Release-(857)-939x1178.jpg");
            AddMappedImageUrl("7/r_General%20Site%20-%20Press%20Release%20(857).jpg",
                "Development/General-Site-Press-Release-(857)-478x600.jpg");
            AddMappedImageUrl("7/o_General%20Site%20-%20Press%20Release%20(Page%20Layout).jpg",
                "Development/General-Site-Press-Release-(Page-Layout)-770x1002.jpg");
            AddMappedImageUrl("7/r_General%20Site%20-%20Press%20Release%20(Page%20Layout).jpg",
                "Development/General-Site-Press-Release-(Page-Layout)-461x600.jpg");
            AddMappedImageUrl("7/o_General%20Site%20-%20Product%20Detail%20(6890N%20GC).jpg",
                "Development/General-Site-Product-Detail-(6890N-GC)-940x1034.jpg");
            AddMappedImageUrl("7/r_General%20Site%20-%20Product%20Detail%20(6890N%20GC).jpg",
                "Development/General-Site-Product-Detail-(6890N-GC)-545x600.jpg");
            AddMappedImageUrl("7/o_General%20Site%20-%20Product%20Detail%20(Page%20Layout).jpg",
                "Development/General-Site-Product-Detail-(Page-Layout)-770x866.jpg");
            AddMappedImageUrl("7/r_General%20Site%20-%20Product%20Detail%20(Page%20Layout).jpg",
                "Development/General-Site-Product-Detail-(Page-Layout)-533x600.jpg");
            AddMappedImageUrl("7/o_Git%20-%20Pending%20changes%20-%20yes%20or%20no.png",
                "Development/Git-Pending-changes-yes-or-no-1113x650.png");
            AddMappedImageUrl("7/r_Git%20-%20Pending%20changes%20-%20yes%20or%20no.png",
                "Development/Git-Pending-changes-yes-or-no-600x350.png");
            AddMappedImageUrl("7/o_Google-Analytics-Account-Home.png",
                "Development/Google-Analytics-Account-Home-767x435.png");
            AddMappedImageUrl("7/r_Google-Analytics-Account-Home.png",
                "Development/Google-Analytics-Account-Home-600x340.png");
            AddMappedImageUrl("7/o_Google-Site-Search-1.png",
                "Development/Google-Site-Search-1-989x2006.png");
            AddMappedImageUrl("7/r_Google-Site-Search-1.png",
                "Development/Google-Site-Search-1-296x600.png");
            AddMappedImageUrl("7/o_Google-Site-Search-2.png",
                "Development/Google-Site-Search-2-989x1810.png");
            AddMappedImageUrl("7/r_Google-Site-Search-2.png",
                "Development/Google-Site-Search-2-328x600.png");
            AddMappedImageUrl("7/o_Google-Site-Search-3.png",
                "Development/Google-Site-Search-3-989x1556.png");
            AddMappedImageUrl("7/r_Google-Site-Search-3.png",
                "Development/Google-Site-Search-3-381x600.png");
            AddMappedImageUrl("8/o_Hyper-V%20Staggered%20Start.png",
                "Infrastructure/Hyper-V-Staggered-Start-1153x595.png");
            AddMappedImageUrl("8/r_Hyper-V%20Staggered%20Start.png",
                "Infrastructure/Hyper-V-Staggered-Start-600x310.png");
            AddMappedImageUrl("7/o_IIS-404.png",
                "Development/IIS-404-1006x185.png");
            AddMappedImageUrl("7/r_IIS-404.png",
                "Development/IIS-404-600x110.png");
            AddMappedImageUrl("8/o_Jameson%20Datacenter%20-%202009-09-13.jpg",
                "Infrastructure/Jameson-Datacenter-2009-09-13-909x747.jpg");
            AddMappedImageUrl("8/r_Jameson%20Datacenter%20-%202009-09-13.jpg",
                "Infrastructure/Jameson-Datacenter-2009-09-13-600x493.jpg");
            AddMappedImageUrl("8/o_Jameson%20Datacenter%20-%20AD%20domain%20structure.png",
                "Infrastructure/Jameson-Datacenter-AD-domain-structure-305x605.png");
            AddMappedImageUrl("8/r_Jameson%20Datacenter%20-%20AD%20domain%20structure.png",
                "Infrastructure/Jameson-Datacenter-AD-domain-structure-302x600.png");
            AddMappedImageUrl("8/o_Jameson%20Datacenter%20-%20Hardware%20(2009-09-13).jpg",
                "Infrastructure/Jameson-Datacenter-Hardware-(2009-09-13)-890x674.jpg");
            AddMappedImageUrl("8/r_Jameson%20Datacenter%20-%20Hardware%20(2009-09-13).jpg",
                "Infrastructure/Jameson-Datacenter-Hardware-(2009-09-13)-600x454.jpg");
            AddMappedImageUrl("8/o_Jameson%20Datacenter%20-%20Logical%20(2009-09-13).jpg",
                "Infrastructure/Jameson-Datacenter-Logical-(2009-09-13)-995x614.jpg");
            AddMappedImageUrl("8/r_Jameson%20Datacenter%20-%20Logical%20(2009-09-13).jpg",
                "Infrastructure/Jameson-Datacenter-Logical-(2009-09-13)-600x370.jpg");
            AddMappedImageUrl("7/o_Kpi_ShowProblems.gif",
                "Development/Kpi_ShowProblems-16x16.gif");
            AddMappedImageUrl("7/o_kpidefault-0.gif",
                "Development/kpidefault-0-16x16.gif");
            AddMappedImageUrl("7/o_kpidefault-1.gif",
                "Development/kpidefault-1-16x16.gif");
            AddMappedImageUrl("7/o_kpidefault-2.gif",
                "Development/kpidefault-2-16x16.gif");
            AddMappedImageUrl("7/o_Linked%20Files%20in%20Visual%20Studio%20Solutions.JPG",
                "Development/Linked-Files-in-Visual-Studio-Solutions-372x577.JPG");
            AddMappedImageUrl("7/o_LINQPad.png",
                "Development/LINQPad-821x873.png");
            AddMappedImageUrl("7/r_LINQPad.png",
                "Development/LINQPad-564x600.png");
            AddMappedImageUrl("7/o_list-item-sprites-1.0.png",
                "Development/list-item-sprites-1.0-400x400.png");
            AddMappedImageUrl("7/o_list-items-sprite-design.png",
                "Development/list-items-sprite-design-1594x1001.png");
            AddMappedImageUrl("7/r_list-items-sprite-design.png",
                "Development/list-items-sprite-design-600x377.png");
            AddMappedImageUrl("7/o_Macro%20Output%20Pane.png",
                "Development/Macro-Output-Pane-686x273.png");
            AddMappedImageUrl("7/r_Macro%20Output%20Pane.png",
                "Development/Macro-Output-Pane-600x239.png");
            AddMappedImageUrl("8/o_Microsoft%20.NET%20Framework%204%20Setup%20Requirements.png",
                "Infrastructure/Microsoft-.NET-Framework-4-Setup-Requirements-503x470.png");
            AddMappedImageUrl("8/o_Microsoft%20Security%20Essentials%20-%20trojans.png",
                "Infrastructure/Microsoft-Security-Essentials-trojans-800x560.png");
            AddMappedImageUrl("8/r_Microsoft%20Security%20Essentials%20-%20trojans.png",
                "Infrastructure/Microsoft-Security-Essentials-trojans-600x420.png");
            AddMappedImageUrl("7/r_Modal-Popup-Window-Constrained-Height.png",
                "Development/Modal-Popup-Window-Constrained-Height-460x190.png");
            AddMappedImageUrl("7/o_Modal-Popup-Window-Elements.png",
                "Development/Modal-Popup-Window-Elements-649x261.png");
            AddMappedImageUrl("7/r_Modal-Popup-Window-Elements.png",
                "Development/Modal-Popup-Window-Elements-600x241.png");
            AddMappedImageUrl("9/r_MOSS-2007-Development-Environment.jpg",
                "SharePoint/MOSS-2007-Development-Environment-600x456.jpg");
            AddMappedImageUrl("9/o_MOSS-2007-Development-Environment.jpg",
                "SharePoint/MOSS-2007-Development-Environment-785x596.jpg");
            AddMappedImageUrl("9/o_MOSS%202007%20Publishing%20Content%20Type%20Hierarchy.png",
                "SharePoint/MOSS-2007-Publishing-Content-Type-Hierarchy-568x597.png");
            AddMappedImageUrl("9/o_MOSS%202007%20Search%20Scope%20bug.jpg",
                "SharePoint/MOSS-2007-Search-Scope-bug-799x564.jpg");
            AddMappedImageUrl("9/r_MOSS%202007%20Search%20Scope%20bug.jpg",
                "SharePoint/MOSS-2007-Search-Scope-bug-600x424.jpg");
            AddMappedImageUrl("9/o_MOSS%202007%20Search%20Scope%20bug%20-%20workaround.jpg",
                "SharePoint/MOSS-2007-Search-Scope-bug-workaround-796x564.jpg");
            AddMappedImageUrl("9/r_MOSS%202007%20Search%20Scope%20bug%20-%20workaround.jpg",
                "SharePoint/MOSS-2007-Search-Scope-bug-workaround-600x425.jpg");
            AddMappedImageUrl("9/o_MOSS2007-WS2008-Operations(Admin).jpg",
                "SharePoint/MOSS2007-WS2008-Operations(Admin)-1027x792.jpg");
            AddMappedImageUrl("9/r_MOSS2007-WS2008-Operations(Admin).jpg",
                "SharePoint/MOSS2007-WS2008-Operations(Admin)-600x463.jpg");
            AddMappedImageUrl("9/o_MOSS2007-WS2008-Operations(non-Admin).jpg",
                "SharePoint/MOSS2007-WS2008-Operations(non-Admin)-1024x744.jpg");
            AddMappedImageUrl("9/r_MOSS2007-WS2008-Operations(non-Admin).jpg",
                "SharePoint/MOSS2007-WS2008-Operations(non-Admin)-600x436.jpg");
            AddMappedImageUrl("9/o_MOSS2007-WS2008-Operations(non-Admin)-closeup.jpg",
                "SharePoint/MOSS2007-WS2008-Operations(non-Admin)-closeup-414x225.jpg");
            AddMappedImageUrl("15/o_MSDN%20blog%20-%20Combined%20Views.png",
                "Personal/MSDN-blog-Combined-Views-1136x503.png");
            AddMappedImageUrl("15/r_MSDN%20blog%20-%20Combined%20Views.png",
                "Personal/MSDN-blog-Combined-Views-600x266.png");
            AddMappedImageUrl("7/o_MSDN%20blog%20home%20-%20CSS%20disabled.png",
                "Development/MSDN-blog-home-CSS-disabled-989x1810.png");
            AddMappedImageUrl("7/r_MSDN%20blog%20home%20-%20CSS%20disabled.png",
                "Development/MSDN-blog-home-CSS-disabled-328x600.png");
            AddMappedImageUrl("15/o_MSDN%20blog%20-%20Referrals%20by%20Category.png",
                "Personal/MSDN-blog-Referrals-by-Category-689x444.png");
            AddMappedImageUrl("15/r_MSDN%20blog%20-%20Referrals%20by%20Category.png",
                "Personal/MSDN-blog-Referrals-by-Category-600x387.png");
            AddMappedImageUrl("15/o_MSDN%20blog%20-%20Total%20Posts%20by%20Month.png",
                "Personal/MSDN-blog-Total-Posts-by-Month-699x384.png");
            AddMappedImageUrl("15/r_MSDN%20blog%20-%20Total%20Posts%20by%20Month.png",
                "Personal/MSDN-blog-Total-Posts-by-Month-600x330.png");
            AddMappedImageUrl("15/o_MSDN%20blog%20-%20Total%20Posts%20by%20Year.png",
                "Personal/MSDN-blog-Total-Posts-by-Year-699x362.png");
            AddMappedImageUrl("15/r_MSDN%20blog%20-%20Total%20Posts%20by%20Year.png",
                "Personal/MSDN-blog-Total-Posts-by-Year-600x311.png");
            AddMappedImageUrl("10/o_My%20Windows%20Explorer%20Jump%20List%20-%20Win7.png",
                "My-System/My-Windows-Explorer-Jump-List-Win7-360x283.png");
            AddMappedImageUrl("10/o_My%20Windows%20Explorer%20Jump%20List%20-%20WS2008R2.png",
                "My-System/My-Windows-Explorer-Jump-List-WS2008R2-333x298.png");
            AddMappedImageUrl("8/o_Old%20Jameson%20Datacenter%20-%20Disk%20Configuration.png",
                "Infrastructure/Old-Jameson-Datacenter-Disk-Configuration-697x552.png");
            AddMappedImageUrl("8/r_Old%20Jameson%20Datacenter%20-%20Disk%20Configuration.png",
                "Infrastructure/Old-Jameson-Datacenter-Disk-Configuration-600x475.png");
            AddMappedImageUrl("8/o_Old%20Jameson%20Datacenter%20-%20DNS%20Configuration.png",
                "Infrastructure/Old-Jameson-Datacenter-DNS-Configuration-794x246.png");
            AddMappedImageUrl("8/r_Old%20Jameson%20Datacenter%20-%20DNS%20Configuration.png",
                "Infrastructure/Old-Jameson-Datacenter-DNS-Configuration-600x186.png");
            AddMappedImageUrl("8/o_Old%20Jameson%20Datacenter%20-%20System%20Architecture.png",
                "Infrastructure/Old-Jameson-Datacenter-System-Architecture-987x757.png");
            AddMappedImageUrl("8/r_Old%20Jameson%20Datacenter%20-%20System%20Architecture.png",
                "Infrastructure/Old-Jameson-Datacenter-System-Architecture-600x460.png");
            AddMappedImageUrl("8/o_Old%20Jameson%20Datacenter%20-%20TCP-IP%20Configuration.png",
                "Infrastructure/Old-Jameson-Datacenter-TCP-IP-Configuration-960x754.png");
            AddMappedImageUrl("8/r_Old%20Jameson%20Datacenter%20-%20TCP-IP%20Configuration.png",
                "Infrastructure/Old-Jameson-Datacenter-TCP-IP-Configuration-600x471.png");
            AddMappedImageUrl("15/o_Outlook-folders-after-Thread-Compressor.png",
                "Personal/Outlook-folders-after-Thread-Compressor-334x675.png");
            AddMappedImageUrl("15/r_Outlook-folders-after-Thread-Compressor.png",
                "Personal/Outlook-folders-after-Thread-Compressor-297x600.png");
            AddMappedImageUrl("15/o_Outlook-folders-and-archive-structure.png",
                "Personal/Outlook-folders-and-archive-structure-334x675.png");
            AddMappedImageUrl("15/r_Outlook-folders-and-archive-structure.png",
                "Personal/Outlook-folders-and-archive-structure-297x600.png");
            AddMappedImageUrl("9/o_Publishing%20Site%20-%20BlueBand%20Master%20Page.png",
                "SharePoint/Publishing-Site-BlueBand-Master-Page-1007x593.png");
            AddMappedImageUrl("9/r_Publishing%20Site%20-%20BlueBand%20Master%20Page.png",
                "SharePoint/Publishing-Site-BlueBand-Master-Page-600x353.png");
            AddMappedImageUrl("9/o_Reusable-Content.png",
                "SharePoint/Reusable-Content-1006x857.png");
            AddMappedImageUrl("9/r_Reusable-Content.png",
                "SharePoint/Reusable-Content-600x511.png");
            AddMappedImageUrl("9/o_Reusable-Content-edit-mode.png",
                "SharePoint/Reusable-Content-edit-mode-1011x713.png");
            AddMappedImageUrl("9/r_Reusable-Content-edit-mode.png",
                "SharePoint/Reusable-Content-edit-mode-600x423.png");
            AddMappedImageUrl("9/o_Reusable-Content-List.png",
                "SharePoint/Reusable-Content-List-991x1285.png");
            AddMappedImageUrl("9/r_Reusable-Content-List.png",
                "SharePoint/Reusable-Content-List-463x600.png");
            AddMappedImageUrl("9/o_Reusable-Content-missing-content.png",
                "SharePoint/Reusable-Content-missing-content-1006x353.png");
            AddMappedImageUrl("9/r_Reusable-Content-missing-content.png",
                "SharePoint/Reusable-Content-missing-content-600x211.png");
            AddMappedImageUrl("10/o_Scheduled%20Tasks%20-%20COLOSSUS.jpg",
                "My-System/Scheduled-Tasks-COLOSSUS-1131x224.jpg");
            AddMappedImageUrl("10/r_Scheduled%20Tasks%20-%20COLOSSUS.jpg",
                "My-System/Scheduled-Tasks-COLOSSUS-600x119.jpg");
            AddMappedImageUrl("9/o_SharePoint-2010-Custom-Sign-In-Page.png",
                "SharePoint/SharePoint-2010-Custom-Sign-In-Page-1012x576.png");
            AddMappedImageUrl("9/r_SharePoint-2010-Custom-Sign-In-Page.png",
                "SharePoint/SharePoint-2010-Custom-Sign-In-Page-600x342.png");
            AddMappedImageUrl("9/o_SharePoint-2010-OOTB-Sign-In-Page-1.png",
                "SharePoint/SharePoint-2010-OOTB-Sign-In-Page-1-600x250.png");
            AddMappedImageUrl("9/o_SharePoint-2010-OOTB-Sign-In-Page-2.png",
                "SharePoint/SharePoint-2010-OOTB-Sign-In-Page-2-600x250.png");
            AddMappedImageUrl("9/r_SharePoint-Designer-Error-Creating-Control.png",
                "SharePoint/SharePoint-Designer-Error-Creating-Control-600x305.png");
            AddMappedImageUrl("9/o_SharePoint-Designer-Error-Creating-Control.png",
                "SharePoint/SharePoint-Designer-Error-Creating-Control-756x384.png");
            AddMappedImageUrl("9/o_SharePoint%20Development%20VM.png",
                "SharePoint/SharePoint-Development-VM-793x419.png");
            AddMappedImageUrl("9/r_SharePoint%20Development%20VM.png",
                "SharePoint/SharePoint-Development-VM-600x317.png");
            AddMappedImageUrl("9/o_SharePoint%20Error%20Page.png",
                "SharePoint/SharePoint-Error-Page-1024x624.png");
            AddMappedImageUrl("9/r_SharePoint%20Error%20Page.png",
                "SharePoint/SharePoint-Error-Page-600x366.png");
            AddMappedImageUrl("7/o_SharePoint-Server-2010-Publishing-Portal.png",
                "Development/SharePoint-Server-2010-Publishing-Portal-1006x627.png");
            AddMappedImageUrl("7/r_SharePoint-Server-2010-Publishing-Portal.png",
                "Development/SharePoint-Server-2010-Publishing-Portal-600x374.png");
            AddMappedImageUrl("9/o_Silverlight%20-%20No%20menu%20open.png",
                "SharePoint/Silverlight-No-menu-open-447x300.png");
            AddMappedImageUrl("9/o_Silverlight%20-%20Obscured%20menu.png",
                "SharePoint/Silverlight-Obscured-menu-447x300.png");
            AddMappedImageUrl("9/r_Silverlight%20-%20Unobscured%20menu%20(windowless).png",
                "SharePoint/Silverlight-Unobscured-menu-(windowless)-447x300.png");
            AddMappedImageUrl("7/o_Solution-Explorer-Step-1.JPG",
                "Development/Solution-Explorer-Step-1-314x452.JPG");
            AddMappedImageUrl("10/o_Taskbar-Shortcuts.jpg",
                "My-System/Taskbar-Shortcuts-301x96.jpg");
            AddMappedImageUrl("7/o_Technology-Toolbox-Blog-Home.png",
                "Development/Technology-Toolbox-Blog-Home-1058x1699.png");
            AddMappedImageUrl("7/r_Technology-Toolbox-Blog-Home.png",
                "Development/Technology-Toolbox-Blog-Home-374x600.png");
            AddMappedImageUrl("7/o_Technology-Toolbox-Blog-Home-CSS-disabled.png",
                "Development/Technology-Toolbox-Blog-Home-CSS-disabled-989x1640.png");
            AddMappedImageUrl("7/r_Technology-Toolbox-Blog-Home-CSS-disabled.png",
                "Development/Technology-Toolbox-Blog-Home-CSS-disabled-362x600.png");
            AddMappedImageUrl("7/o_Technology-Toolbox-Blog-Post.png",
                "Development/Technology-Toolbox-Blog-Post-1058x1595.png");
            AddMappedImageUrl("7/r_Technology-Toolbox-Blog-Post.png",
                "Development/Technology-Toolbox-Blog-Post-398x600.png");
            AddMappedImageUrl("7/o_Technology-Toolbox-Color-Palette.png",
                "Development/Technology-Toolbox-Color-Palette-556x644.png");
            AddMappedImageUrl("7/r_Technology-Toolbox-Color-Palette.png",
                "Development/Technology-Toolbox-Color-Palette-518x600.png");
            AddMappedImageUrl("7/o_Technology-Toolbox-Contact.png",
                "Development/Technology-Toolbox-Contact-1058x1072.png");
            AddMappedImageUrl("7/r_Technology-Toolbox-Contact.png",
                "Development/Technology-Toolbox-Contact-592x600.png");
            AddMappedImageUrl("7/o_Technology-Toolbox-Contact-CAPTCHA.png",
                "Development/Technology-Toolbox-Contact-CAPTCHA-1058x1189.png");
            AddMappedImageUrl("7/r_Technology-Toolbox-Contact-CAPTCHA.png",
                "Development/Technology-Toolbox-Contact-CAPTCHA-534x600.png");
            AddMappedImageUrl("7/o_Technology-Toolbox-Contact-validation.png",
                "Development/Technology-Toolbox-Contact-validation-1058x1258.png");
            AddMappedImageUrl("7/r_Technology-Toolbox-Contact-validation.png",
                "Development/Technology-Toolbox-Contact-validation-505x600.png");
            AddMappedImageUrl("7/o_Technology-Toolbox-Error-404.png",
                "Development/Technology-Toolbox-Error-404-1006x494.png");
            AddMappedImageUrl("7/r_Technology-Toolbox-Error-404.png",
                "Development/Technology-Toolbox-Error-404-600x295.png");
            AddMappedImageUrl("7/o_Technology-Toolbox-Error-Generic.png",
                "Development/Technology-Toolbox-Error-Generic-1006x494.png");
            AddMappedImageUrl("7/r_Technology-Toolbox-Error-Generic.png",
                "Development/Technology-Toolbox-Error-Generic-600x295.png");
            AddMappedImageUrl("7/o_Technology-Toolbox-Home.png",
                "Development/Technology-Toolbox-Home-1058x1179.png");
            AddMappedImageUrl("7/r_Technology-Toolbox-Home.png",
                "Development/Technology-Toolbox-Home-538x600.png");
            AddMappedImageUrl("7/o_Technology-Toolbox-Home%20(Page%20Layout).png",
                "Development/Technology-Toolbox-Home-(Page-Layout)-1058x1185.png");
            AddMappedImageUrl("7/r_Technology-Toolbox-Home%20(Page%20Layout).png",
                "Development/Technology-Toolbox-Home-(Page-Layout)-536x600.png");
            AddMappedImageUrl("8/o_Technology-Toolbox-Infrastructure.jpg",
                "Infrastructure/Technology-Toolbox-Infrastructure-1019x677.jpg");
            AddMappedImageUrl("8/r_Technology-Toolbox-Infrastructure.jpg",
                "Infrastructure/Technology-Toolbox-Infrastructure-600x399.jpg");
            AddMappedImageUrl("7/o_Technology-Toolbox-Services.png",
                "Development/Technology-Toolbox-Services-1058x871.png");
            AddMappedImageUrl("7/r_Technology-Toolbox-Services.png",
                "Development/Technology-Toolbox-Services-600x494.png");
            AddMappedImageUrl("7/o_Technology-Toolbox-Services-with-Grid.png",
                "Development/Technology-Toolbox-Services-with-Grid-1058x872.png");
            AddMappedImageUrl("7/r_Technology-Toolbox-Services-with-Grid.png",
                "Development/Technology-Toolbox-Services-with-Grid-600x495.png");
            AddMappedImageUrl("7/o_Technology-Toolbox-Solution-Architecture.jpg",
                "Development/Technology-Toolbox-Solution-Architecture-726x629.jpg");
            AddMappedImageUrl("7/r_Technology-Toolbox-Solution-Architecture.jpg",
                "Development/Technology-Toolbox-Solution-Architecture-600x520.jpg");
            AddMappedImageUrl("7/o_Technology-Toolbox-Style-Guide.png",
                "Development/Technology-Toolbox-Style-Guide-989x5388.png");
            AddMappedImageUrl("7/r_Technology-Toolbox-Style-Guide.png",
                "Development/Technology-Toolbox-Style-Guide-110x600.png");
            AddMappedImageUrl("7/o_TFS%202010%20-%20DefaultTemplate%20-%20Overview.png",
                "Development/TFS-2010-DefaultTemplate-Overview-232x431.png");
            AddMappedImageUrl("7/o_TFS-2010-Increment-Version-Step-1.png",
                "Development/TFS-2010-Increment-Version-Step-1-279x744.png");
            AddMappedImageUrl("7/r_TFS-2010-Increment-Version-Step-1.png",
                "Development/TFS-2010-Increment-Version-Step-1-225x600.png");
            AddMappedImageUrl("7/o_TFS-2010-Increment-Version-Step-2.png",
                "Development/TFS-2010-Increment-Version-Step-2-255x921.png");
            AddMappedImageUrl("7/r_TFS-2010-Increment-Version-Step-2.png",
                "Development/TFS-2010-Increment-Version-Step-2-166x600.png");
            AddMappedImageUrl("7/o_TFS-2010-Increment-Version-Step-3.png",
                "Development/TFS-2010-Increment-Version-Step-3-292x586.png");
            AddMappedImageUrl("7/o_TFS%202010%20-%20Update%20Drop%20Location.png",
                "Development/TFS-2010-Update-Drop-Location-254x464.png");
            AddMappedImageUrl("9/r_TFS%20Lite%20-%20WSS%20v2.jpg",
                "SharePoint/TFS-Lite-WSS-v2-600x452.jpg");
            AddMappedImageUrl("9/o_TFS%20Lite%20-%20WSS%20v2.jpg",
                "SharePoint/TFS-Lite-WSS-v2-788x594.jpg");
            AddMappedImageUrl("9/r_TFS%20Lite%20-%20WSS%20v3.jpg",
                "SharePoint/TFS-Lite-WSS-v3-600x363.jpg");
            AddMappedImageUrl("9/o_TFS%20Lite%20-%20WSS%20v3.jpg",
                "SharePoint/TFS-Lite-WSS-v3-991x599.jpg");
            AddMappedImageUrl("9/o_Tugboat-Home.png",
                "SharePoint/Tugboat-Home-991x2008.png");
            AddMappedImageUrl("9/r_Tugboat-Home.png",
                "SharePoint/Tugboat-Home-296x600.png");
            AddMappedImageUrl("9/o_Tugboat-Home-Page-Layout.png",
                "SharePoint/Tugboat-Home-Page-Layout-723x1464.png");
            AddMappedImageUrl("9/r_Tugboat-Home-Page-Layout.png",
                "SharePoint/Tugboat-Home-Page-Layout-296x600.png");
            AddMappedImageUrl("9/o_Tugboat-Map-Firefox.png",
                "SharePoint/Tugboat-Map-Firefox-1017x1025.png");
            AddMappedImageUrl("9/r_Tugboat-Map-Firefox.png",
                "SharePoint/Tugboat-Map-Firefox-595x600.png");
            AddMappedImageUrl("9/o_Tugboat-Map-IE8.png",
                "SharePoint/Tugboat-Map-IE8-1024x1020.png");
            AddMappedImageUrl("9/r_Tugboat-Map-IE8.png",
                "SharePoint/Tugboat-Map-IE8-600x598.png");
            AddMappedImageUrl("9/o_Tugboat-SharePoint-2010-Bold-Links.png",
                "SharePoint/Tugboat-SharePoint-2010-Bold-Links-1008x599.png");
            AddMappedImageUrl("9/r_Tugboat-SharePoint-2010-Bold-Links.png",
                "SharePoint/Tugboat-SharePoint-2010-Bold-Links-600x357.png");
            AddMappedImageUrl("9/o_Tugboat-SharePoint-2010-Step-1.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-1-1008x911.png");
            AddMappedImageUrl("9/r_Tugboat-SharePoint-2010-Step-1.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-1-600x542.png");
            AddMappedImageUrl("9/o_Tugboat-SharePoint-2010-Step-2.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-2-1008x599.png");
            AddMappedImageUrl("9/r_Tugboat-SharePoint-2010-Step-2.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-2-600x357.png");
            AddMappedImageUrl("9/o_Tugboat-SharePoint-2010-Step-3.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-3-1008x599.png");
            AddMappedImageUrl("9/r_Tugboat-SharePoint-2010-Step-3.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-3-600x357.png");
            AddMappedImageUrl("9/o_Tugboat-SharePoint-2010-Step-3-bad.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-3-bad-1005x617.png");
            AddMappedImageUrl("9/r_Tugboat-SharePoint-2010-Step-3-bad.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-3-bad-600x368.png");
            AddMappedImageUrl("9/o_Tugboat-SharePoint-2010-Step-4.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-4-1008x599.png");
            AddMappedImageUrl("9/r_Tugboat-SharePoint-2010-Step-4.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-4-600x357.png");
            AddMappedImageUrl("9/o_Tugboat-SharePoint-2010-Step-5.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-5-1008x599.png");
            AddMappedImageUrl("9/r_Tugboat-SharePoint-2010-Step-5.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-5-600x357.png");
            AddMappedImageUrl("9/o_Tugboat-SharePoint-2010-Step-6.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-6-1008x599.png");
            AddMappedImageUrl("9/r_Tugboat-SharePoint-2010-Step-6.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-6-600x357.png");
            AddMappedImageUrl("9/o_Tugboat-SharePoint-2010-Step-7.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-7-1008x599.png");
            AddMappedImageUrl("9/r_Tugboat-SharePoint-2010-Step-7.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-7-600x357.png");
            AddMappedImageUrl("9/o_Tugboat-SharePoint-2010-Step-8.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-8-1008x599.png");
            AddMappedImageUrl("9/r_Tugboat-SharePoint-2010-Step-8.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-8-600x357.png");
            AddMappedImageUrl("9/o_Tugboat-SharePoint-2010-Step-8-bad.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-8-bad-1007x616.png");
            AddMappedImageUrl("9/r_Tugboat-SharePoint-2010-Step-8-bad.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-8-bad-600x367.png");
            AddMappedImageUrl("9/o_Tugboat-SharePoint-2010-Step-8-good.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-8-good-1007x617.png");
            AddMappedImageUrl("9/r_Tugboat-SharePoint-2010-Step-8-good.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-8-good-600x368.png");
            AddMappedImageUrl("9/o_Tugboat-SharePoint-2010-Step-9.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-9-1008x599.png");
            AddMappedImageUrl("9/r_Tugboat-SharePoint-2010-Step-9.png",
                "SharePoint/Tugboat-SharePoint-2010-Step-9-600x357.png");
            AddMappedImageUrl("9/o_Tugboat-Solution-Upgrade.jpg",
                "SharePoint/Tugboat-Solution-Upgrade-768x2262.jpg");
            AddMappedImageUrl("9/r_Tugboat-Solution-Upgrade.jpg",
                "SharePoint/Tugboat-Solution-Upgrade-499x1472.jpg");
            AddMappedImageUrl("9/o_Tugboat-Specials-List.png",
                "SharePoint/Tugboat-Specials-List-1005x794.png");
            AddMappedImageUrl("9/r_Tugboat-Specials-List.png",
                "SharePoint/Tugboat-Specials-List-600x474.png");
            AddMappedImageUrl("9/o_Tugboat-Specials-List-XsltListViewWebPart.png",
                "SharePoint/Tugboat-Specials-List-XsltListViewWebPart-1006x544.png");
            AddMappedImageUrl("9/r_Tugboat-Specials-List-XsltListViewWebPart.png",
                "SharePoint/Tugboat-Specials-List-XsltListViewWebPart-600x324.png");
            AddMappedImageUrl("9/o_Tugboat-Too-Many-Specials.png",
                "SharePoint/Tugboat-Too-Many-Specials-1006x689.png");
            AddMappedImageUrl("9/r_Tugboat-Too-Many-Specials.png",
                "SharePoint/Tugboat-Too-Many-Specials-600x411.png");
            AddMappedImageUrl("9/r_Tugboat-WelcomePageLayout1.png",
                "SharePoint/Tugboat-WelcomePageLayout1-600x285.png");
            AddMappedImageUrl("7/o_Typed%20DataSet%20example%20(ScorecardData).png",
                "Development/Typed-DataSet-example-(ScorecardData)-723x398.png");
            AddMappedImageUrl("7/r_Typed%20DataSet%20example%20(ScorecardData).png",
                "Development/Typed-DataSet-example-(ScorecardData)-600x330.png");
            AddMappedImageUrl("7/o_Upgraded%20TFS%20project%20site.png",
                "Development/Upgraded-TFS-project-site-987x1332.png");
            AddMappedImageUrl("7/r_Upgraded%20TFS%20project%20site.png",
                "Development/Upgraded-TFS-project-site-445x600.png");
            AddMappedImageUrl("7/o_Upgraded%20TFS%20project%20site%20with%20RS%20error.png",
                "Development/Upgraded-TFS-project-site-with-RS-error-988x792.png");
            AddMappedImageUrl("7/r_Upgraded%20TFS%20project%20site%20with%20RS%20error.png",
                "Development/Upgraded-TFS-project-site-with-RS-error-600x481.png");
            AddMappedImageUrl("9/r_Variation-Page-Propagation%20(after).jpg",
                "SharePoint/Variation-Page-Propagation-(after)-600x436.jpg");
            AddMappedImageUrl("9/o_Variation-Page-Propagation%20(after).jpg",
                "SharePoint/Variation-Page-Propagation-(after)-670x487.jpg");
            AddMappedImageUrl("9/r_Variation-Page-Propagation%20(before).jpg",
                "SharePoint/Variation-Page-Propagation-(before)-600x436.jpg");
            AddMappedImageUrl("9/o_Variation-Page-Propagation%20(before).jpg",
                "SharePoint/Variation-Page-Propagation-(before)-704x512.jpg");
            AddMappedImageUrl("7/r_Windows-Explorer-Step-1.JPG",
                "Development/Windows-Explorer-Step-1-600x379.JPG");
            AddMappedImageUrl("7/o_Windows-Explorer-Step-1.JPG",
                "Development/Windows-Explorer-Step-1-767x485.JPG");
            AddMappedImageUrl("8/o_Windows%20Server%20Backup%20-%20Recovery%20Wizard%20Bug.png",
                "Infrastructure/Windows-Server-Backup-Recovery-Wizard-Bug-756x586.png");
            AddMappedImageUrl("8/r_Windows%20Server%20Backup%20-%20Recovery%20Wizard%20Bug.png",
                "Infrastructure/Windows-Server-Backup-Recovery-Wizard-Bug-600x465.png");
        }

        private void AddMappedImageUrl(
            string oldImagePath,
            string newImagePath)
        {
            var key = string.Concat(_oldImageBasePath, "/", oldImagePath);

            var newImageUrl = new Uri(
                string.Concat(
                    "https://",
                    _newImageHost,
                    _newImageBasePath,
                    "/",
                    newImagePath));

            _imageUrlMap.Add(key, newImageUrl);
        }

        private string GetRelativeUrl(Uri url)
        {
            if (url == null)
            {
                throw new ArgumentNullException("url");
            }

            if (url.IsAbsoluteUri == true && url.Host != _oldImageHost)
            {
                throw new ArgumentException(
                    $"URL ({url}) does not contain expected host ("
                        + _oldImageHost + ").",
                    "url");
            }

            string relativeUrl = null;

            if (url.IsAbsoluteUri == true)
            {
                relativeUrl = url.PathAndQuery;
            }
            else
            {
                relativeUrl = url.ToString();
            }

            return relativeUrl;
        }

        public Uri GetMappedUrl(Uri url)
        {
            var relativeUrl = GetRelativeUrl(url);

            return _imageUrlMap[relativeUrl];
        }

        public bool IsMappedUrl(Uri url)
        {
            if (url == null)
            {
                throw new ArgumentNullException("url");
            }
            else if (url.IsAbsoluteUri == true && url.Host != _oldImageHost)
            {
                return false;
            }

            var relativeUrl = GetRelativeUrl(url);

            Uri mappedUrl = null;

            return _imageUrlMap.TryGetValue(relativeUrl, out mappedUrl);
        }
    }
}
